import images from "./images";

export const Modules = [
  // Première Année
  {
    id: 0,
    name: "Analyse I",
    prof: "Pr. Hicham Mahdioui",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S1",
    icon: images.analyse,
  },
  {
    id: 1,
    name: "Algèbre I",
    prof: "Pr. Abdellah Bnouhachem",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S1",
    icon: images.analyse,
  },
  {
    id: 2,
    name: "Electrostatique",
    prof: "Pr. Driss Agliz",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S1",
    icon: images.analyse,
  },
  {
    id: 3,
    name: "Magnétostatique",
    prof: "Pr. Abdelfattah Narjis",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S1",
    icon: images.analyse,
  },
  {
    id: 4,
    name: "Informatique I",
    prof: "Pr. Abdenbi Abnaou",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S1",
    icon: images.analyse,
  },
  {
    id: 5,
    name: "Mécanique I",
    prof: "Pr. Abdellah Tihane",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S1",
    icon: images.analyse,
  },
  {
    id: 6,
    name: "Analyse II",
    prof: "Pr. Hicham Mahdioui",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S2",
    icon: images.analyse,
  },
  {
    id: 7,
    name: "Algèbre II",
    prof: "Pr. Lahcen Taoufiq",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S2",
    icon: images.analyse,
  },
  {
    id: 8,
    name: "Electrocinétique I",
    prof: "Pr. Wissam Jenkal",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S2",
    icon: images.analyse,
  },
  {
    id: 9,
    name: "Electrocinétique II",
    prof: "Pr. Marouane ElAzzaoui",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S2",
    icon: images.analyse,
  },
  {
    id: 10,
    name: "Informatique II",
    prof: "Pr. Abdenbi Abnaou",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S2",
    icon: images.analyse,
  },

  {
    id: 11,
    name: "Chimie",
    prof: "Pr. Rachid Salghi",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S2",
    icon: images.analyse,
  },

  // Deuxième année
  {
    id: 12,
    name: "Analyse III",
    prof: "Pr. Lahcen Taoufiq",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S3",
    icon: images.analyse,
  },
  {
    id: 13,
    name: "Topologie",
    prof: "Pr. Said Taarabti",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S3",
    icon: images.analyse,
  },
  {
    id: 14,
    name: "Thermodynamique",
    prof: "Pr. Hicham Meftah",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S3",
    icon: images.analyse,
  },
  {
    id: 15,
    name: "Hydrostatique",
    prof: "Pr. Mbarek Feddaoui",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S3",
    icon: images.analyse,
  },
  {
    id: 16,
    name: "Mécanique 2",
    prof: "Pr. Hamid Essabir",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S3",
    icon: images.analyse,
  },
  {
    id: 17,
    name: "Electronique",
    prof: "Pr. Samira Chabaa",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S3",
    icon: images.analyse,
  },
  {
    id: 18,
    name: "Analyse 4",
    prof: "Pr. Hicham Elboujaoui",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S4",
    icon: images.analyse,
  },
  {
    id: 19,
    name: "Programmation C",
    prof: "Pr. Wissam Jenkal",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S4",
    icon: images.analyse,
  },
  {
    id: 20,
    name: "Electromagnétisme",
    prof: "Pr. Abdellah Tihane",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S4",
    icon: images.analyse,
  },
  {
    id: 21,
    name: "Optique Physique",
    prof: "Pr. Driss Agliz",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S4",
    icon: images.analyse,
  },
  {
    id: 22,
    name: "Les Probabilités",
    prof: "Pr. Ghizlane Lakhnati",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S4",
    icon: images.analyse,
  },
  {
    id: 23,
    name: "D.A.O",
    prof: "Pr. Lahoucine Belarche",
    res: "hamza",
    td: "hamza td",
    ds: "hamza ds",
    level: "S4",
    icon: images.analyse,
  },
];
